[package]
name = "gscom"
version = "0.1.0"
edition = "2021"

[dependencies]
gdk4-sys = "0.9.0"
#gtk = { version = "0.9.1", package = "gtk4", features = ["v4_12"] }
gtk = { version = "0.9.1", package = "gtk4", features = ["v4_8"] }
